# Generated by Django 3.1.7 on 2021-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='Photo', max_length=50, verbose_name='Fotoğraf Adı'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Fotoğraf'),
        ),
    ]