# Generated by Django 3.1.7 on 2021-04-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210415_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Fotoğraf'),
        ),
    ]