# Generated by Django 3.1.7 on 2021-04-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210415_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Fotoğraf:'),
        ),
    ]