# Generated by Django 3.1.7 on 2021-04-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20210415_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Fotoğraf Adı:'),
        ),
    ]